name: DeathTimer
version: '${project.version}'
main: com.asynclab.github.xiaomo.deathtimer
api-version: '1.20'
load: STARTUP
softdepend: [PlaceholderAPI]
authors: [YokeXM]
commands:
  DeathTimer:
    description: "Manager Command"
    aliases:
      - dt
    usage: "§c/dt reload"
  alive:
    description: "Respawn player"
permissions:
  deathtimer.ok:
    description: "/alive ok"