name: DeathTimer
version: '${plugin_version}'
main: ${plugin_group}.DeathTimer
api-version: '1.20'
load: STARTUP
softdepend: [ PlaceholderAPI ]
authors: [ ${ plugin_authors } ]
description: ${plugin_description}
commands:
  DeathTimer:
    description: "Manager Command"
    aliases:
      - dt
    usage: "§c/dt reload"
  alive:
    description: "Respawn player"
permissions:
  ${plugin_group}.reload:
    description: "/dt reload"
    default: op
  ${plugin_group}.clear:
    description: "/dt clear"
    default: op