name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

      - name: Create GitHub Release
        id: create_release
        uses: gh-actions/gh-release@master
        with:
          token: ${{ secrets.TOKEN }}
          draft: false
          prerelease: false
          files: build/libs/*.jar
        env:
          TOKEN: ${{ secrets.TOKEN }}
